#!/usr/bin/env python

from argparse import ArgumentParser
from pyyeti.nastran import op4


parser = ArgumentParser(description="List contents of op4 file(s)")

parser.add_argument(
    "input_file", metavar="INFILE", help="file to read", type=str, nargs="+"
)

args = parser.parse_args()

for name in args.input_file:
    print()
    print(name)
    op4.dir(name)
